### ISSUE TITLE
Question about sections classified as "-" and ""

### ISSUE THREAD

**Issue by hpbl** [gprana/READMEClassifier#2] opened 2019-06-04 17:34 UTC
Hello sir,

Using your classifier, I got some sections classified with section code "-" and some with no code at all.

Could you please explain what those mean, I didn't really understand them from reading your paper.

Thank you very much.

**Comment by gprana** [comment] 2019-06-04 23:02
Hi,
'-' is the label for "Exclusion", which is typically assigned to sections of README files that aren't in English. As for section having no output code, it may be caused by no label having probability higher than 0.5 for the particular section. The actual probability scores can be checked using classifier_train_model_predict_proba.py for training followed by classifier_classify_target_predict_proba.py for prediction. This will generate a list of input sections along with probabilities for each label for the section as CSV file model/target_proba.csv in the project directory.

Hope it helps.

**Closed as completed** 2019-06-05 11:10 UTC
